books/urls.py
from django.urls import path
from . import views

from django.conf import settings 
from django.conf.urls.static import static 

from .views import book_detail, books_list, random_list, CreateBook, UpdateBook, DeleteBook, new_books_list

# app_name = 'books'

urlpatterns = [
    path('', views.books_list, name='books'),
    path('books/', views.new_books_list, name='new_books_list'),
    path('book_detail/<int:id>/<slug:slug>', views.book_detail, name = 'book_detail'),
    path('random_list', views.random_list, name='random_list'),
    path('books/new_book/', CreateBook.as_view(), name='new_book'),
    path('books/<int:pk>/book_delete/', DeleteBook.as_view(), name='book_delete'),
    path('books/<int:pk>/book_edit/', UpdateBook.as_view(), name='book_edit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task2/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('books.urls', 'books'), namespace='books')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.conf import settings

class Books(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    image = models.ImageField(upload_to='book_images', blank=True)
    book_file = models.FileField(upload_to='book_files', blank=True)
    

class Meta:
        ordering = ('title',)
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

def __str__(self):
    return self.title

# def __unicode__(self):
#     return self.title + " / " + self.author

#добавить filefield 

books/forms.py
from django import forms
from .models import Books

class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ('image', 'title', 'author')

books/views.py
from django.shortcuts import render, get_object_or_404
from .models import Books
import random
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import BookForm


# Create your views here.

def books_list(request):
    books = Books.objects.all()
    return render(request,'books_list.html', {'books': books})

def new_books_list(request):
    books = Books.objects.filter(image=True)
    return render(request, 'new_books_list.html', {'books': books})

def book_detail(request):
    book = get_object_or_404(Books)
    return render(request, 'book_detail.html', {'book_detail': book})

def random_list(request):
    random_list = list(Books.objects.all())
    random_list = random.sample(random_list, 3)
    return render(request, 'random_list.html', {'random_list': random_list})

class CreateBook(CreateView):
    form_class = BookForm
    template_name = 'new_book.html'
    success_url = reverse_lazy('books:books_list')


class UpdateBook(UpdateView):
    model = Books
    form_class = BookForm
    books = Books.objects.all()
    template_name = 'book_edit.html'
    success_url = reverse_lazy('books:new_books_list')



class DeleteBook(DeleteView):
    model = Books
    template_name = 'book_delete.html'
    success_url = reverse_lazy('books:new_books_list')






# def frontpage(request):
#     products = list(Product.objects.all())

#     products = random.sample(products, 9)

#     return render(request, 'front-page.html', {'products': products})

books/templates/base.html
    {% load static %}
<html>
    <head>
        <title>Bookshelf</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        
    </head>
    

    {% block content %}

    {% endblock %}

    

</html>

    

</html>

books/templates/book_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
    <h1>Delete book</h1>
    <form action="" method="post">
        {% csrf_token %}
    <p>Вы уверены что хотите удалить "{{ book.title }}"?</p>
    <input type="submit" value="Да" />
    </form>
{% endblock %}

books/templates/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<body>
    
    <div class='container'> 
        <!-- {% for book in books %}   -->
        <div class='col-md-4'>
            <img class="avatar-img" src="{{book.image.url}}">
            <h2> {{book.title}}</h2>
            <h5> {{book.author}}</h5>
            <h5> {{book.genre}}</h5>   
        </div>  
        <!-- {% endfor %} -->
    </div>

</body>
{% endblock %}

books/templates/book_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<h1>Редактирование книги</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Обновить данные" />
</form>
{% endblock %}

books/templates/books_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
    {% include 'header.html' %}

    <div class='container'>
        {% for book in books %}  
        <div class='col-md-4'>
            <img class="avatar-img" src="{{book.image.url}}">
            <h2> <a href='#'></a>{{book.title}}</h2>
            <h5> {{book.author}}</h5>
            <h5> {{book.genre}}</h5> 
            <a href="{% url 'books:book_edit' book.pk %}">Редактировать книгу</a>
            <a href="{% url 'books:book_delete' book.pk %}">Удалить книгу</a>

        </div>  
        {% endfor %}    
    </div>
        
    
</body>

{% endblock %}

books/templates/header.html
{% load static %}
<div class = "page-header">
    <h1><a href = "/"> Bookshelf</a></h1>
    <ul id='header-links'>
        <li><a href='{% url "books:books" %}'>Главная страница</a></li>
        <li><a href="{% url 'books:random_list' %}" >Новинки</a></li>
        <li><a href='#'>Что почитать</a></li>
        <li><a href="{% url 'books:new_book' %}">Добавить новую книгу</a></li>
    </ul>
</div>

books/templates/new_book.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<h1>Добавление новой книги</h1>
<form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <input type="submit" value="Сохранить" />
</form>
{% endblock %}

books/templates/new_books_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<body>

    <div class="container">
    
            {% for book in books %}
                    <div class='col-md-4'>
                    <img class="image-img" src="{{book.image.url}}">
                    <h2>{{book.title}}</h2>
                    <h5>{{book.author}}</h5>
                </div>
    
            {% endfor %}
        </div>
</body>        
{% endblock %}

books/templates/random_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<div class='container'>
    {% for book in random_list %}  
    <div class='col-md-4'>
        <img class="avatar-img" src="{{book.image.url}}">
        <h2> <a href='#'></a>{{book.title}}</h2>
        <h5> {{book.author}}</h5>
        <h5> {{book.genre}}</h5>   
    </div>  
    {% endfor %}    
{% endblock %}